name: AWS Lambda CICD
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1
      - name: Create AWS Lambda Function
        run: |
          aws lambda create-function --function-name auth-lambda --runtime java17 --handler auth.App::handleRequest --role arn:aws:iam::332769750459:role/lambda-ex --zip-file fileb://target/auth-1.0.jar
        continue-on-error: true  
      - name: Update Lambda Function    
        run: aws lambda update-function-code --function-name auth-lambda --zip-file fileb://target/auth-1.0.jar
